name:                katalog
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/hawnzug/katalog#readme
license:             BSD3
author:              hawnzug
maintainer:          hawnzug@gmail.com
copyright:           hawnzug
category:            Web
extra-source-files:
- README.md

dependencies:
- base

library:
  source-dirs: src
  dependencies:
  - vector
  - text
  - containers
  - megaparsec
  - parser-combinators
  - prettyprinter

executables:
  katalog:
    source-dirs:      katalog
    main:             Main.hs
    dependencies:
    - katalog

tests:
  katalog-tests:
    source-dirs: tests
    main:        Main.hs
    dependencies:
    - text
    - filepath
    - containers
    - tasty
    - tasty-hunit
    - tasty-golden
    - tasty-quickcheck
    - QuickCheck
    - katalog
